### ISSUE TITLE
NATS JetStream support

### ISSUE THREAD

**Issue by stefanmeschke** [lerenn/asyncapi-codegen#109]
First things first: Thanks for this awesome package! 💙
Are there any plans to support [NATS JetStream](https://docs.nats.io/nats-concepts/jetstream)?

**Comment by lerenn** [comment]
Hello @stefanmeschke ! Thanks for you kind words :blush: 

Well, I plan to support a maximum of brokers and, with an already supported basic NATS adapter, Jetstream mode is a must have. I don't have a lot of time to do it right now, but I'll implement it in the near future (especially if you have a need).

However, if you are in a hurry and/or want to give a try yourself, I invite you to take a look to existing brokers implementations to implement the Jetstream version.

The brokers adapters implement [this interface](https://github.com/lerenn/asyncapi-codegen/blob/74fe7b0331a283baf2d5e384117c0953e7d1be0a/pkg/extensions/broker.go#L95C1-L103C2):

```golang
// BrokerController represents the functions that should be implemented to connect
// the broker to the generated code.
type BrokerController interface {
	// Publish a message to the broker
	Publish(ctx context.Context, channel string, mw BrokerMessage) error

	// Subscribe to messages from the broker
	Subscribe(ctx context.Context, channel string) (BrokerChannelSubscription, error)
}
```

If you achieve to implement these two functions with Jetstream to Publish/Subscribe messages, then you have a NATS Jetstream implementation! Also, you can use the examples to test your implementation if you want.

Here are the files: 
 - [NATS](https://github.com/lerenn/asyncapi-codegen/blob/main/pkg/extensions/brokers/nats/nats.go)
 - [Kafka](https://github.com/lerenn/asyncapi-codegen/blob/main/pkg/extensions/brokers/kafka/kafka.go)

If you want to try it, do not hesitate to ping me anytime for help. Otherwise, no worry, I'll implement it this month :smiley:

**Comment by lerenn** [comment]
Hey @stefanmeschke !

Thanks for the amazing work ! :relaxed: 

For the first point, I don't see the drawback of having only one consumer, so we can try do design it this way ! But I don't understand what you need exactly: one consumer for all subscriptions on the AsyncAPI ? If that's it, we can add a subject to listen to the only consumer each time `Subscribe` is call and do the message reception in two steps:
1. One goroutine that listen to the consumer and send the message to the goroutine corresponding to the correct subscription
2. One goroutine by subscription (A.K.A. call on `Subscribe`) that await a message from the reception goroutine and redirect it to the user (through `sub.TransmitReceivedMessage`)

For the second point, I see that you ACK the message at the end of `MessagesHandler()`, what would you ideally want? A retry mecanism? A fail mecanism? For the last one, we could ACK the message before sending it to the user (so above `sub.TransmitReceivedMessage`) so if the ACK fails, we don't send the message to the user. But again I'm not really experienced with JetStream, and that maybe not what you want.

Also, I tried to implement it quickly yesterday and put the branch on the repository if you want to take a look/reuse some of my code (spoiler alert: it doesn't work :smile: ): https://github.com/lerenn/asyncapi-codegen/tree/add-nats-jetstream-broker. But in order to match your use-case, and because community co-working is nice, I would prefer to use your version :relaxed:

**Comment by stefanmeschke** [comment]
Hey @lerenn 

Hope you have/had nice Holidays! 🎄

I've created a draft pull request with your recommendations from above.

> For the second point, I see that you ACK the message at the end of MessagesHandler(), what would you ideally want?

Ideally I could handle this in the business logic. Just thought of returning custom errors: `RetryableError` and `NonRetryableError`. 🤔  At the moment I don't see any possibility to do this due to the architecture, but I'm pretty sure that this would be awesome.
In the draft pull request I've just ack'd optimistically, which is in 99.999999% of the cases cool, but for the other things (short outage of other dependencies etc.) this could lead to unwanted behaviour in the app.

Really looking forward to your thoughts on the PR. 😊 


Cheers,
Stefan

**Comment by lerenn** [comment]
Hello @stefanmeschke !

Thanks for this awesome work ! :pray: 
And no worries, this is really nice of you to propose this PR in the first place (also Christmas time is no easy time :smile:).

For the returning of custom errors, that could be a great improvement! I think it would better to create another issue on the subject to add it to this broker, but others as well.

I'll take a look at your PR asap (lots going on on my side as well).
Thanks again :relieved:

**Comment by lerenn** [comment]
Also, I don't see exactly what you are suggesting with the Retry/NoRetry error in this sentence:

> Ideally I could handle this in the business logic. Just thought of returning custom errors: `RetryableError` and `NonRetryableError`

Would you means that the subscriber could retry (or not) to retrieve the message, or the publisher to retry (or not) the sending of the message?

Please do not hesitate to elaborate on this for me to better understand what you would see for this problem :pray:

**Comment by stefanmeschke** [comment]
Oki. Lemme try to explain it what I meant:

In JetStream consumers can acknowledge messages or not acknowledge messages (with or without delay). Based on the policies this message will den re-delivered (push consumer) or re-pulled (pull-consumer). This is very handy when e.g. something went wrong in the business logic (thinking of a short outage from a dependent service or something else). At the moment there is no connection of the message to the JetStream message once this it was parsed and delivered to the subscriber. Therefore this message gets acknowledged in the broker, which is from my point of view not ideal, because something could happen in the subsequent business logic, which could/should led to e.g. not acknowledging this message.
So it's all about the consumption, not the publishing.

I personally thought of something in the context, which gets passed to the subscription. 🤷

Hope this makes sense? 🙂

**Comment by lerenn** [comment]
Okay, thanks for the explanation, I understand it better ! :pray: 

So now we have:

```mermaid
flowchart LR

Emitter-->Broker;
Broker-->Reception;
Reception--ACK-->Broker;
Reception-->BusinessLogic;
BusinessLogic-->Failure[Possible failure]
```

So it would great to have:

```mermaid
flowchart LR

Emitter-->Broker;
Broker-->Reception;
Reception-->BusinessLogic;
BusinessLogic-->Failure[Possible failure]
Failure-->ReceptionRetry;
Broker-->ReceptionRetry;
ReceptionRetry-->BusinessLogicRetry;
BusinessLogicRetry-->Success;
Success--ACK-->Broker;
```

I'll create a ticket based on that, if that's okay for you ! :)

**Comment by stefanmeschke** [comment]
Yes and no. 😅 
In case of NATS JetStream it is something like this:

```mermaid
flowchart TB

Emitter-->Broker;
Broker-->Reception;
Reception-->BusinessLogic;
BusinessLogic-->Success;
Success--ACK-->Broker;
BusinessLogic-->Failure
Failure--NACK with or without delay-->Broker;
```

I would also be up to contribute on this feature. Maybe we could elaborate on the new issue how we wan't to achieve this (code wise)?

First though: This is super specific to any broker. Therefore I thought to make it more general and to handle then errors in the brokers separately.

**Comment by lerenn** [comment]
Oh right! It makes more sense with your schema.
I'll create a new issue :)
